function a = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  A = IMPORTFILE(FILENAME) reads data from text file FILENAME for the
%  default selection.  Returns the numeric data.
%
%  A = IMPORTFILE(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  a = importfile("C:\Users\Acer\OneDrive - Universidade de Coimbra\Ambiente de Trabalho\Model transfer\Coagulacoes_FTIR_C&C_24\Coagulações_triplicados\0111010192231a.csv", [3, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 22-Oct-2024 16:15:45

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [3, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2, "Encoding", "UTF-8");

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ";";

% Specify column names and types
opts.VariableNames = ["Var1", "Amostra394PorLaboratrioDataSegundafeiraSetembro232024"];
opts.SelectedVariableNames = "Amostra394PorLaboratrioDataSegundafeiraSetembro232024";
opts.VariableTypes = ["string", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Var1", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "Var1", "EmptyFieldRule", "auto");
opts = setvaropts(opts, "Amostra394PorLaboratrioDataSegundafeiraSetembro232024", "TrimNonNumeric", true);
opts = setvaropts(opts, "Amostra394PorLaboratrioDataSegundafeiraSetembro232024", "ThousandsSeparator", ",");

% Import the data
a = readtable(filename, opts);

%% Convert to output type
a = table2array(a);
end