function [Data,Name] = importfile(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  UNTITLED = IMPORTFILE(FILE) reads data from the first worksheet in
%  the Microsoft Excel spreadsheet file named FILE.  Returns the numeric
%  data.
%
%  UNTITLED = IMPORTFILE(FILE, SHEET) reads from the specified worksheet.
%
%  UNTITLED = IMPORTFILE(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  Untitled = importfile("C:\Users\Acer\OneDrive - Universidade de Coimbra\Ambiente de Trabalho\Model transfer\ABIAM\Resultados FTIR\0112080147237\0112080147237.xlsx", "0112080147237", [6, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 16-Jul-2024 18:21:42

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [6, Inf];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 8);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = dataLines(1, :);

% Specify column names and types
opts.VariableNames = ["Var1", "T", "Var3", "Var4", "T_1", "Var6", "Var7", "T_2"];
opts.SelectedVariableNames = ["T", "T_1", "T_2"];
opts.VariableTypes = ["char", "double", "char", "char", "double", "char", "char", "double"];

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var3", "Var4", "Var6", "Var7"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var3", "Var4", "Var6", "Var7"], "EmptyFieldRule", "auto");

% Import the data
Data = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = dataLines(idx, :);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    Data = [Data; tb]; %#ok<AGROW>
end

%% Convert to output type
Data = table2array(Data);


%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 7);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = dataLines(1, :);

% Specify column names and types
opts.VariableNames = ["cm1", "Var2", "Var3", "cm1_1", "Var5", "Var6", "cm1_2"];
opts.SelectedVariableNames = ["cm1", "cm1_1", "cm1_2"];
opts.VariableTypes = ["string", "char", "char", "string", "char", "char", "string"];

% Specify variable properties
opts = setvaropts(opts, ["cm1", "Var2", "Var3", "cm1_1", "Var5", "Var6", "cm1_2"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["cm1", "Var2", "Var3", "cm1_1", "Var5", "Var6", "cm1_2"], "EmptyFieldRule", "auto");

% Import the data
Name = readmatrix(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = dataLines(idx, :);
    tb = readmatrix(workbookFile, opts, "UseExcel", false);
    Name = [Name; tb]; %#ok<AGROW>
end


end